name: Test Release
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test-${{ github.sha }}
          release_name: Test Release ${{ github.sha }}
          body: This is a test release
          draft: true
          prerelease: true
