name: Test Release
on:
  push:
    branches:
      - '**'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "test-${{ github.run_id }}" \
            --title "Test Release ${{ github.run_id }}" \
            --notes "This is a test release" \
            --draft \
            --prerelease
